services:
  - type: web
    name: cyberdocs-app
    env: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: cyberdocs-mysql.mysql.database.azure.com
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: ADMIN_EMAIL
        value: danielnjuguna9042@gmail.com
      - key: ADMIN_PASSWORD
        value: 123456
      # The following sensitive values should be set in the Render dashboard
      # - key: UPLOADTHING_SECRET
      #   value: <YOUR_UPLOADTHING_SECRET>
      # - key: UPLOADTHING_APP_ID
      #   value: <YOUR_UPLOADTHING_APP_ID>
    # Define the root directory for the build output if needed
    # rootDir: dist # Usually not needed if startCommand points correctly 
    staticPublishPath: ./
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Content-Type
        value: application/javascript; charset=utf-8 